# Generated by Django 5.0 on 2024-01-09 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, verbose_name='Author')),
                ('rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('number_of_pages', models.PositiveIntegerField(default=0, verbose_name='Number_of_Pages')),
                ('language', models.CharField(choices=[('eng', 'Eng'), ('per', 'Per')], max_length=3, verbose_name='Language')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('publish', models.BooleanField(default=False, verbose_name='Publish')),
            ],
        ),
        migrations.CreateModel(
            name='SaveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaveItem_book', to='books.book', verbose_name='Book')),
            ],
        ),
    ]
