# Generated by Django 5.0 on 2024-01-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default=None, upload_to='book/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
