# Generated by Django 5.0 on 2024-01-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='price_of_one_book',
            field=models.PositiveIntegerField(default=0, verbose_name='Price of one Book'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
